# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-17 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
